name: Core
author: elijuh
version: ${project.version}
depend: [Vault, TAB, PlaceholderAPI]
main: me.elijuh.core.Core
permissions:
  core.*:
    children:
    - core.admin
  core.admin:
    children:
      - core.staff
      - core.gamemode
      - core.warp.*
      - core.setwarp
      - core.delwarp
      - core.teleport
      - core.fix
      - core.fix.all
      - core.clear
      - core.clear.others
      - core.feed
      - core.feed.others
      - core.heal
      - core.heal.others
      - core.fly
      - core.fly.others
      - core.staffmode.interact
      - core.economy
  core.staff:
    children:
      - worldedit.navigation.jumpto.tool
      - worldedit.navigation.thru.tool
      - core.invsee
    default: op
  core.gamemode:
    default: op
  core.warp.*:
    default: op
  core.setwarp:
    default: op
  core.delwarp:
    default: op
  core.teleport:
    default: op
  core.fix:
    default: op
  core.fix.all:
    default: op
  core.clear:
    default: op
  core.clear.others:
    default: op
  core.feed:
    default: op
  core.feed.others:
    default: op
  core.heal:
    default: op
  core.heal.others:
    default: op
  core.fly:
    default: op
  core.fly.others:
    default: op
  core.freeze:
    default: op
  core.staffmode.interact:
    default: op
  core.economy:
    default: op
  core.invsee:
    default: op
  core.invsee.edit:
    default: op
